config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts
  get 'search' => 'posts#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :start_day, presence: true
    validates :finish_day, presence: true
    validates :title, presence: true
    
    def self.sort(selection)
        case selection
            when 'id_asc'
                return all.order(id: :ASC)
            when 'id_desc'
                return all.order(id: :DESC)
            when 'start_day_close'
                return all.order(start_day: :ASC)
            when 'start_day_far'
                return all.order(start_day: :DESC)
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "スケジュール登録が完了しました。"
      redirect_to :root
    else
      render "new"
    end
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    @post = Post.new(post_params)
    if @post.update(post_params)
      flash[:notice] = "ID:#{@post.id}のスケジュールの編集が完了しました。"
      redirect_to :root
    else
      render "edit"
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "スケジュールを削除しました。"
    redirect_to :root
  end
  
  # ソート機能
  def search
    selection = params[:keyword]
    @posts = Post.sort(selection)
  end
  
  
  private
  def post_params
    params.require(:post).permit(:title, :start_day, :finish_day, :memo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <header>
        <h1>スケジュール管理アプリ</h1>
      </header>
      <%= yield %>
      <footer>
        <p>現在の時刻は<%= Time.zone.now.to_s(:datetime_jp) %>です。</p>
      <footer>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<h2>スケジュール編集</h2>
<%= render "shared/error", object: @post %>
<%= form_for @post do |f| %>
    <table>
        <tr>
            <th><%= f.label :title, "タイトル" %></th>
            <td><%= f.text_field :title %></td>
        </tr>
        
        <tr>
            <th><%= f.label :start_day, "開始日時" %></th>
            <td><%= f.datetime_field :start_day %></td>
        </tr>
        
        <tr>
            <th><%= f.label :finish_day, "終了日時" %></th>
            <td><%= f.datetime_field :finish_day %></td>
        </tr>
        
        <tr>
            <th><%= f.label :memo, "メモ" %></th>
            <td><%= f.text_area :memo %></td>
        </tr>
    </table>
    <div>
        <ul>
            <li><%= f.submit "編集を完了する" %></li>
            <li><%= link_to "スケジュール一覧に戻る", posts_path %></li>
        </ul>
    </div>
<% end %>

app/views/posts/index.html.erb
<h2>スケジュール一覧</h2>
    <%= render "shared/flash" %>
    <%= render "shared/select" %>
    <%= render "shared/result" %>
    <div>
        <p><%= link_to "スケジュール登録", new_post_path %></p>
    </div>

app/views/posts/new.html.erb
<h2>スケジュール登録</h2>
<%= render "shared/error", object: @post %>
<%= form_for @post do |f| %>
    <table>
        <tr>
            <th><%= f.label :title, "タイトル" %></th>
            <td><%= f.text_field :title %></td>
        </tr>
        
        <tr>
            <th><%= f.label :start_day, "開始日時" %></th>
            <td><%= f.datetime_field :start_day %></td>
        </tr>
        
        <tr>
            <th><%= f.label :finish_day, "終了日時" %></th>
            <td><%= f.datetime_field :finish_day %></td>
        </tr>
        
        <tr>
            <th><%= f.label :memo, "メモ" %></th>
            <td><%= f.text_area :memo %></td>
        </tr>
        
    </table>
    <div>
        <ul>
            <li><%= f.submit "登録する" %></li>
            <li><%= link_to "スケジュール一覧に戻る", posts_path %></li>
        </ul>
    </div>
<% end %>

app/views/posts/search.html.erb
<h2>スケジュール一覧</h2>
    <%= render "shared/flash" %>
    <%= render "shared/select" %>
    <%= render "shared/result" %>
    <div>
        <p><%= link_to "スケジュール登録", new_post_path %></p>
    </div>

app/views/posts/show.html.erb
<h2>スケジュール詳細</h2>
    <table>
        <tr>
            <th>ID</th>
            <td><%= @post.id %></td>
        </tr>
        <tr>
            <th>タイトル</th>
            <td><%= @post.title %></td>
        </tr>
        <tr>
            <th>開始日時</th>
            <td><%= @post.start_day.to_s(:datetime_jp) %></td>
        </tr>
        <tr>
            <th>終了日時</th>
            <td><%= @post.finish_day.to_s(:datetime_jp) %></td>
        </tr>
        <tr>
            <th>メモ</th>
            <td><%= @post.memo %></td>
        </tr>
        <tr>
            <th>作成日時</th>
            <td><%= @post.created_at.to_s(:datetime_jp) %></td>
        </tr>
    </table>
    <div>
        <ul>
            <li><%= link_to "スケジュール一覧に戻る", posts_path %></li>
            <li><%= link_to "スケジュールを編集", edit_post_path(@post.id) %></li>
            <li><%= link_to "スケジュールを削除", post_path(@post.id), method: :delete, data: { confirm: "削除しますか？？"} %></li>
        </ul>
    </div>

app/views/shared/_error.html.erb
<% if object.errors.any? %>
    <% object.errors.full_messages.each do |message| %>
        <ul>
            <li><%= message %></li>
        </ul>
    <% end %>
<% end %>

app/views/shared/_flash.html.erb
    <% if flash.notice %>
        <p class="notice"><%= flash.notice %></p>
    <% end %>

app/views/shared/_result.html.erb
   <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>タイトル</th>
                <th>開始日時</th>
                <th>終了日時</th>
                <th>メモ</th>
                <th>作成日時</th>
                <th>確認</th>
                <th>編集</th>
                <th>削除</th>
            </tr>
        </thead>
            
        <tbody>
            <% @posts.each do |post| %>
                <tr>
                    <td><%= post.id %></td>
                    <td><%= post.title %></td>
                    <td><%= post.start_day.to_s(:datetime_jp) %></td>
                    <td><%= post.finish_day.to_s(:datetime_jp) %></td>
                    <td><%= post.memo %></td>
                    <td><%= post.created_at.to_s(:datetime_jp) %></td>
                    <td>
                        <%= link_to "確認", post_path(post) %>
                    </td>
                    <td>
                        <%= link_to "編集", edit_post_path(post) %>
                    </td>
                    <td>
                        <%= link_to "削除", post_path(post), method: :delete, data: { confirm: "削除しますか？？"} %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>

app/views/shared/_select.html.erb
<%= form_with model: @post, url: search_path, method: :get, local: true do |form| %>
        <%= form.select :keyword, [['登録が古い順', 'id_asc'],
                                    ['登録が新しい順', 'id_desc'],
                                    ['開始日時が近い順', 'start_day_close'],
                                    ['開始日時が遠い順', 'start_day_far'],
                                   ] %>
        <%= form.submit "並び替え" %>
        
<% end %>